# Macro file for proton on Beryllium simulation
# 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
# Change the default number of workers (in multi-threading mode) 
#/run/numberOfThreads 4
#
# Initialize kernel
/run/initialize
#
/control/verbose 2
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
# 
# proton 5 MeV to the direction (0.,0.,1.)
#
/gun/particle proton
/gun/energy 5 MeV
/tracking/verbose 0
#
/run/beamOn 100000000
